- great_tables/_gt_data.py
- great_tables/_locations.py
- great_tables/_spanners.py
- great_tables/_styles.py
- great_tables/_tbl_data.py
- great_tables/gt.py
- tests/test_locations.py
- tests/test_spanners.py
This PR fleshes out the Spanner class, to prepare for using it in rendering!
Main things added:
* Spanner class is not a Sequence of SpannerInfo entries
* Basic `spanner_print_matrix()` and `empty_spanner_matrix()`
- Note that currently the matrix is just a list of dictionaries 😅 (but I wonder if this will work out okay? It seems like the renderers aren't using a lot of matrix stuff fingers crossed)
* dataclasses for cell styling (`Cell*`) and location selection (`_locate.Loc*`)
* generic `_locate.resolve()` function
- Simple implementation for `resolve(LocSpannerColumns, ...)`
> Feat spanners

- great_tables/_gt_data.py
- great_tables/_locations.py
- great_tables/_spanners.py
- great_tables/_tbl_data.py
- great_tables/gt.py
- tests/test_gt.py
- tests/test_gt_data.py
- tests/test_spanners.py
- tests/test_tbl_data.py
This PR completes adding basic tab_spanner functionality (except in the rendering sense).
As part of the implementation, it fleshes out these pieces:
* cols_move
* eval_select for tidyselection on a DataFrame
> Feat tab spanners

- great_tables/_gt_data.py
- great_tables/_source_notes.py
- great_tables/data/__init__.py
- great_tables/gt.py
- tests/test_gt.py
This PR fixes SourceNotes and Body code, so it does not mutate the underlying data. This was causing issues where re-running code could continuously append notes, or error due to body mutations (e.g. a numeric column becoming a string column)
Note that I removed the custom SourceNotes class, in favor of using a list of strings
> fix: do not mutate sourcenotes or body

- .github/workflows/ci-tests.yaml
This PR deploys to pypi whenever we make a github release. It only runs if the tests pass. However, note it does not require the docs to build (since they are in a different workflow, and it's a bit tricky, but not impossible to do?!). There are ways to test that don't involve full blown attempting to deploy. But given how early it is, I vote for us merging, doing a release, and then seeing what happens 😈.
> ci: deploy to pypi on release

- great_tables/gt.py
- pyproject.toml
This PR upgrades to the latest quartodoc, which can correctly document the methods on the `GT` class.
Note that I had to remove the methods section from GT, which apparently quartodoc does not support  😓
> Docs fix upgrade quartodoc

- great_tables/_gt_data.py
- great_tables/_heading.py
- tests/test_heading.py
This PR changes `tab_header()`, so that it creates and returns a copy of GTData, and puts a new Heading object on it (vs mutating the existing heading).
This prevents heading mutations from creating headings in places where tab_heading isn't called.
> fix: tab_header no longer mutates GTData

- great_tables/_boxhead.py
- great_tables/_footnotes.py
- great_tables/_formats.py
- great_tables/_gt_data.py
- great_tables/_heading.py
- great_tables/_locale.py
- great_tables/_options.py
- great_tables/_row_groups.py
- great_tables/_stubhead.py
- great_tables/_utils_render_html.py
- great_tables/gt.py
- tests/test_formats.py
This PR freezes our dataclasses so we couldn't mutate them if we wanted to†. The `GTData._replace()` method can be used to return a copy of GTData, with specific attributes replaced.
I'm going to take out the API classes, so we can type their methods a bit better (currently, the type system doesn't know they can access a `._replace` method)
†: except by using `super().__setattr__("<attribute_name>", <value>)`, which should be used sparingly!
TODO:
* code paths it'd be helpful to tour Michael through:
- locales
- options
> refactor: freeze dataclasses

- great_tables/_gt_data.py
- tests/test_options.py
This PR adds a test file for the options api with 1 test.
> tests: add test of options

- docs/_quarto.yml
- docs/examples-qmd/GT.qmd
- docs/examples-qmd/fmt-number.qmd
- docs/examples-qmd/table-manipulation.qmd
- docs/examples/index.qmd
- docs/get-started/basic-formatting.qmd
- docs/get-started/column-selection.qmd
- great_tables/__init__.py
- great_tables/_boxhead.py
- great_tables/_formats.py
- great_tables/_heading.py
- great_tables/_source_notes.py
- great_tables/_spanners.py
- great_tables/_stubhead.py
- tests/test_formats.py
This PR removes all datasets except exibble from the top-level module.
When users attempt to import a dataset that previously worked, they're given a friendly message:
```python
from great_tables import airquality
```
```
ImportError: Cannot import dataset from top-level of package. Please import from data submodule:
from great_tables.data import airquality
```
> refactor!: remove datasets from top-level module (except exibble)

- great_tables/_scss.py
- great_tables/css/gt_styles_default.scss
- great_tables/gt.py
- pyproject.toml
- tests/test_scss.py
This PR replaces libsass, by using python + the webcolors package to assemble the css used by GT.
The main changes are:
* use `string.Template` to fill in parameters in the css file
* replace the function `font-color` with variables like `font_color_table_background`
* add a python function `font_color()` for generating the font color values.
I added some basic tests of `font_color`, but it could be useful to try and test a more exhaustive set. I think the main weakness of this process like hinges on `font_color()` being as robust as `scss` functions like `color.red()`.
TODO: I haven't fully removed the libsass code, but can do it before merging, if this ends up seeming like the way to go!
> refactor!: replace libsass code with webcolors

- great_tables/_scss.py
- great_tables/css/gt_styles_default.scss
- tests/__snapshots__/test_scss.ambr
- tests/test_scss.py
This PR addresses an issue with addition not being supported in our rendering the scss file (https://github.com/posit-dev/great-tables/issues/60#issuecomment-1846329398).
It adds the following:
* a function `css_add`, and new variables in the scss for the results of calling it on other variables.
* a compress argument to compile_scss, to toggle whether or not we strip spaces from the generated css
* generates a test snapshot of css generated from default GT options
> fix: handle addition in scss template

- docs/examples/index.qmd
Added a table to the Examples documentation (`/docs/examples/index.qmd`) that shows how to embed html links into the table, a common need in a table.
- Ref: #69
- [ x I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
> add hyperlinks in table example

- docs/_quarto.yml
- great_tables/__init__.py
- great_tables/_gt_data.py
- great_tables/_locations.py
- great_tables/_styles.py
- great_tables/_tab_create_modify.py
- great_tables/_tbl_data.py
- great_tables/_utils_render_html.py
- great_tables/gt.py
- great_tables/loc.py
- great_tables/style.py
- tests/test_tab_create_modify.py
This adds the `tab_style()` method. The method requires `locations` and `style` values which are provided by new classes in the `loc` and `style` submodules.
You could do this:
```
import great_tables as gt
from great_tables import style, loc
from great_tables import exibble
(
gt.GT(exibble)
.tab_style(
style=style.text(color="blue"),
locations=loc.body(columns="num", rows=[0, 1, 2, 3]),
)
.tab_style(
style=style.text(size="25px"),
locations=loc.body(columns=["fctr"], rows=[0, 1, 2, 3]),
)
.tab_style(
style=style.text(color="red"),
locations=loc.body(columns=["fctr"], rows=[1, 2, 3, 4]),
)
.tab_style(
style=style.text(size="10px"),
locations=loc.body(columns=["fctr"], rows=[0, 1, 2, 3]),
)
)
```
Fixes: https://github.com/posit-dev/great-tables/issues/63
> Implement the `tab_style()` method

- great_tables/_locations.py
- great_tables/_spanners.py
- great_tables/_styles.py
- tests/__snapshots__/test_utils_render_html.ambr
- tests/test_locations.py
- tests/test_utils_render_html.py
When adding styles through the `tab_style()` method, it is far more sensible target the most number of cells and use the `columns` and `rows` arguments to constrain the cell selection. This PR enables this behavior so that this
```py
import great_tables as gt
from great_tables import style, loc, md, html
from great_tables import exibble
(
gt.GT(exibble)
.tab_style(
style=style.text(color="red"),
locations=loc.body(),
)
)
```
results in
Fixes: https://github.com/posit-dev/great-tables/issues/76
> Make invocation `loc.body()` default to all columns and rows

- docs/examples/index.qmd
Currently, the example page shows two columns of examples, even when on narrow screens (e.g. on mobile). This PR changes examples to only display in two columns on large screens.
**before:**
**after:**
> docs: single column examples on narrow screens

- docs/_quarto.yml
- great_tables/__init__.py
- great_tables/_locations.py
- great_tables/_styles.py
- great_tables/_tbl_data.py
- great_tables/style.py
- tests/__snapshots__/test_locations.ambr
- tests/test_locations.py
- tests/test_styles.py
This PR implements the `from_column()` behavior from gt, which allows for setting a style based on values in the data.
e.g.
```python
import pandas as pd
from great_tables import GT, exibble, loc, style
df = pd.DataFrame({"x": [1, 2], "color": ["red", "blue"]})
gt = GT(df)
gt.tab_style(
style = style.text(color = style.from_column("color")),
locations = loc.body(columns = ["x"])
)
```
NOTES:
* **scope**: currently only implemented for setting in `loc.body()`, raises if you try to use it with `loc.title()`
* **implementation**: the R gt library handles from_column inside each `fmt_*` function. This PR puts the handling inside `set_style`, by implementing a CellStyle._from_row() method. This gives each style the chance to return a new version of itself based on the data, just before setting …
> feat: add style.from_column, implement for loc.body

- great_tables/_gt_data.py
- great_tables/_spanners.py
- tests/test_spanners.py
This PR fixes `cols_hide()` which was raising an error when multiple columns were specified, due to `set_col_hidden()` not returning anything (my bad!).
Now the new method `set_cols_hidden()`:
* doesn't mutate anything
* returns a new boxhead
> fix: cols_hide

- great_tables/_tab_create_modify.py
- great_tables/_utils_render_html.py
- tests/__snapshots__/test_utils_render_html.ambr
- tests/test_utils_render_html.py
This PR addresses #84 and #85 by fixing support for lists of styles and locations. Previously, only the first style in a StyleInfo.styles list was used, and the locations code needed a lil tweak to accumulate locations
> fix: allow lists of styles and lists of locations

- docs/_quarto.yml
- docs/get-started/basic-header.qmd
- docs/get-started/basic-styling.qmd
This PR adds a new page to Get Started called ["Styling the table body"](https://pr-88--gt-python.netlify.app/get-started/basic-styling), which covers the basics of styling with `loc.body()`. 
Note that I tried to structure Get Started a bit more, by splitting it into Table Structure, Format and Style, and Extra Topics for now:
Happy to discuss / change it to anything useful! It seems like once they're implemented we could add additional pages, like:
* footnotes to the Table Structure section
* styling other locations (like header) to the Format and Style section
TODO:
* Should titles use title case, or just capitalize the first letter?
> docs: get started with styling page

- great_tables/_scss.py
This fixes a `re.sub()` statement in the `compile_scss()` function so that the table ID is inserted before the rule for the `p` element. This corrects a regression where the compiled CSS no longer worked with one of the `re.sub()` statements. With this fix, the rule for the table's `<p>` element is specific to the table (and doesn't affect the page itself).
> Ensure that ID value in compiled CSS is applied to all rules

- docs/_extensions/machow/interlinks/.gitignore
- docs/_extensions/machow/interlinks/_extension.yml
- docs/_extensions/machow/interlinks/interlinks.lua
- docs/_quarto.yml
- docs/styles.css
- great_tables/_boxhead.py
- great_tables/_formats.py
- great_tables/_formats_vals.py
- great_tables/_heading.py
- great_tables/_helpers.py
- great_tables/_source_notes.py
- great_tables/_spanners.py
- great_tables/_stubhead.py
This PR makes use of the `interlinks` Quarto filter so that cross-referencing links (mainly to other methods/functions in the docs site) can be easily added. We also improve the look of the site by adding a `styles.css` file.
> Add interlinks throughout documentation site

- docs/_quarto.yml
- great_tables/_formats.py
- great_tables/gt.py
This adds a basic implementation of the `fmt_datetime()` method, which allows for the formatting of datetime values/strings using separate patterns for the date and time parts. A separator between date and time parts is permitted here through the `sep` argument.
> Add the `fmt_datetime()` method

- docs/_quarto.yml
- docs/get-started/basic-styling.qmd
- docs/get-started/column-selection.qmd
- docs/get-started/row-selection.qmd
- great_tables/_formats.py
- great_tables/_locations.py
- great_tables/_spanners.py
- great_tables/_styles.py
- great_tables/_tbl_data.py
- tests/test_formats.py
- tests/test_locations.py
- tests/test_styles.py
This PR addresses #102 by...
* allowing functions for row selection in `fmt_*` methods
* allowing functions for row selection in `body.*` functions.
* It also allows polars selectors (and anything used by `resolve_rows_i`) in `fmt_*` methods
TODO:
* ~Add simple tests using `fmt()`, and `CellStyle._evaluate_expressions()`~
> Feat selectors

- .github/workflows/ci-docs.yaml
This PR re-adds the deployment url to our docs CI, so there is a clickable link to a PR's preview docs
> ci: restore deploy url

- docs/get-started/index.qmd
The example tab_spanner doesn't use the right name, so the table in the docs isn't created as intended.
Fixes the air quality example so the output table includes the correct columns in the label spanner, as intended by the code.
- Ref: #110
> Fix tab spanner column name

- great_tables/_gt_data.py
- great_tables/_tbl_data.py
- tests/test_tbl_data.py
Addresses #117 by giving a hopefully diagnostic error message, when a pandas DataFrame with duplicate column names is passed: `Column names must be unique. Detected duplicate columns:\n\n <specific list>`
~TODO: we should also fail DataFrames with multi-index columns.~ (done!)
Fixes: https://github.com/posit-dev/great-tables/issues/117
> Fix validate frame

- great_tables/_gt_data.py
- great_tables/_tbl_data.py
- tests/__snapshots__/test_tbl_data.ambr
- tests/test_tbl_data.py
This PR addresses #125 by...
* coercing non-string column names in pandas to strings.
* giving a UserWarning, with details on which columns were coerced
Note that polars requires column names to be strings, so shouldn't be affected by this particular case.
> fix: validate_frame now coerces non string column names

- great_tables/_data_color/base.py
- great_tables/_gt_data.py
- great_tables/_tbl_data.py
- tests/data_color/__snapshots__/test_data_color.ambr
- tests/data_color/test_data_color.py
This corrects the problem with Polars DataFrames not working with the `data_color()` method due to the problem of using Pandas' `tolist()` instead of our own `to_list()` method (which works with both).
> Use `to_list()` method as cross-df solution

- docs/examples/index.qmd
This adds an example (the `sza`/`data_color()` one) to the Examples page.
Fixes: #135
> Add example for sza and `data_color()`

- .gitignore
- docs/_quarto.yml
- great_tables/_gt_data.py
- great_tables/_spanners.py
- great_tables/_utils_render_html.py
- great_tables/gt.py
- tests/test_spanners.py
This adds the `cols_width()` method, which allows for sizing of columns with CSS length or percentage values. The list of columns and sizes is to be provided in a dictionary.
> Add the `cols_width()` method

- docs/_quarto.yml
- great_tables/_options.py
This adds the `opt_align_table_header()` method, which allows us to easily set the horizontal alignment of the title and subtitle to the left, right, or center by using the `"align"` argument.
Fixes: https://github.com/posit-dev/great-tables/issues/148
> Add the `opt_align_table_header()` method

- docs/_quarto.yml
- great_tables/_options.py
This adds the `opt_all_caps()` method. It'll make it easy to get an all-capitalized look is suitable for a table. Using it transforms characters in the column labels, the stub, and in all row groups to (small) capital letters via CSS.
Fixes: https://github.com/posit-dev/great-tables/issues/149
> Add method: `opt_all_caps()`

- docs/_quarto.yml
- great_tables/_options.py
- great_tables/gt.py
Given there is padding in the cells of different locations, we could set these globally through modification of parameters in `tab_options()`. This is cumbersome because cleanly scaling an entire table up and down should involve a single scaling factor, and the user would need to scale current length values for the appropriate padding options and set those in one go.
Having the `opt*` methods `opt_vertical_padding()` and `opt_horizontal_padding()` makes this much easier. The only parameter needed here is `scale`. 
Fixes: https://github.com/posit-dev/great-tables/issues/153
> Add `opt*` methods to vertical and horizontal padding

- great_tables/_options.py
This PR ensures that a single font name could be used as a scalar value instead of a list. It will be internally promoted to a list before options replacement. The associated type annotation is changed here as well.
> Ensure table font names (from `tab_options()`) is accepted as str or list

- docs/_quarto.yml
- great_tables/__init__.py
- great_tables/_helpers.py
This introduces the `system_fonts()` helper function, and this allows for obtaining a list of themed fonts, the collection of which is expected to work well across computing platforms. There are 15 font stacks in total, and the function is useful within `tab_options()` (for the `table_font_names` parameter). 
Fixes: https://github.com/posit-dev/great-tables/issues/157
> Add the `system_fonts()` helper function

- docs/blog/superbowl-squares/_code.py
This PR makes a small tweak to the Super Bowl blogpost, to add a source data reference to Lee Sharpe and the nflverse
> docs: blog superbowl, add source

- .github/workflows/ci-docs.yaml
- great_tables/_locations.py
- great_tables/_tbl_data.py
As `with_row_count` is [deprecated](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.with_row_count.html), it's recommended to use `with_row_index` instead.
> Replace `with_row_count` by `with_row_index` for `Polars`

- great_tables/_boxhead.py
- great_tables/_formats.py
- great_tables/_heading.py
- great_tables/_options.py
- great_tables/_source_notes.py
- great_tables/_spanners.py
- great_tables/_stubhead.py
- great_tables/_styles.py
- great_tables/_tab_create_modify.py
- great_tables/gt.py
This modifies the examples slightly so that the coding style is more in line with the doc site's top-level examples page (and getting started guides).
> Clean up examples in API docs

- great_tables/_boxhead.py
- great_tables/_formats.py
- great_tables/_formats_vals.py
- great_tables/_heading.py
- great_tables/_helpers.py
- great_tables/_locations.py
- great_tables/_options.py
- great_tables/_source_notes.py
- great_tables/_spanners.py
- great_tables/_stubhead.py
- great_tables/_styles.py
- great_tables/_tab_create_modify.py
- great_tables/gt.py
This removes all type annotations from docstrings. They aren't needed since griffe generates them automatically.
> Remove type annotations from docstrings

- docs/_quarto.yml
- great_tables/_options.py
- great_tables/gt.py
- tests/__snapshots__/test_options.ambr
- tests/test_options.py
This PR adds another `opt_*()` method, this time the `opt_table_outline()` method. It lets you easily draw a line around the entire table, setting several options inside `tab_options()` all at once.
> Add the `opt_table_outline()` method

- great_tables/_data_color/base.py
- great_tables/_tbl_data.py
- tests/data_color/test_data_color.py
The `data_color()` method relies on `mizani.palettes.gradient_n_pal()` to create color palette functions. However, In older versions of mizani, a function produced by `gradient_n_pal()` returns `np.nan` when given missing values. The current version of mizani returns `None` on missing values.
This PR provides wider compatibility with mizani by ensuring both behaviors are handled. The only change required is to the list comprehension here
```python
color_vals = [na_color if x is None else x for x in color_vals] 
```
becoming:
```python
color_vals = [na_color if x is None or x != x else x for x in color_vals]
```
Fixes: https://github.com/posit-dev/great-tables/issues/204
> Ensure that np.nan values are replaced with 'na_color=` vals

- great_tables/_data_color/base.py
- great_tables/_tbl_data.py
- tests/data_color/__snapshots__/test_data_color.ambr
- tests/data_color/test_data_color.py
As discovered in https://github.com/posit-dev/great-tables/issues/212, there are a few pernicious edge cases of data frame columns being incompatible with the color-scaling methodology of `.data_color()`. We shouldn't error or disallow these types of cases from working with that method, we should handle them with some logic.
Here are the cases and how they will be dealt with.
(1) Single value in column --> use first color from palette for the single row
```python
df = pd.DataFrame({"x": [1], "y": [3]})
GT(df).data_color("x", palette=["green", "blue"], na_color="red")
```
(2) Single value , multiple rows (rest of the rows are missing) --> use first color from palette and apply `na_color=` to the missing rows
```python
df = pd.DataFrame({"x": [1, None], "y": [3, 4]})
GT(df).data_color("x", …
```
> Handle `.data_color()` edge cases with single val columns / all missing values

- great_tables/_formats.py
This PR just adds some extra documentation to the `.fmt_image()` method.
> Add docs to the `fmt_image()` method

- docs/get-started/table-theme-premade.qmd
This slightly modifies the `opt_horizontal_padding()` example in the documentation. This one is a bit odd because during manual testing, `GT.opt_horizontal_padding(scale=3)` did not seem to work (which was chalked up to a bounds issue in an argument check) but the code shows it does accept a `scale` value of 3---and the API docs also has an example of this working in https://posit-dev.github.io/great-tables/reference/GT.opt_horizontal_padding.html#great_tables.GT.opt_horizontal_padding.
Fixes: https://github.com/posit-dev/great-tables/issues/214
> Fix `opt_horizontal_padding()` example

- great_tables/_data_color/base.py
- great_tables/_scss.py
- tests/__snapshots__/test_options.ambr
- tests/data_color/test_data_color_utils.py
- tests/test_options.py
- tests/test_scss.py
This PR makes it possible for a GT table to have a transparent background by way of using the `"transparent"` color keyword. Previously, there would be an error because color values in `_font_color()` are routed through a **webcolors** function that only accepts CSS color names.
This PR is a more focused version of an earlier version: https://github.com/posit-dev/great-tables/pull/232
Fixes: https://github.com/posit-dev/great-tables/issues/230
> Allow the 'transparent' color (and others) to be used in tab_options(table_background_color == <color>) (supersedes previous PR)

- great_tables/_formats.py
This adds some basic examples for the `fmt_nanoplot()` method.
> Add examples for `fmt_nanoplot()`

- docs/_quarto.yml
- great_tables/_formats.py
- great_tables/_gt_data.py
- great_tables/_substitution.py
- great_tables/_tbl_data.py
- great_tables/_text.py
- great_tables/gt.py
- tests/test_substitutions.py
This PR adds support for substitution functions. It address #182, by adding the following methods:
* `sub_missing`: substitutes any missing values. This includes both null and nan.
* polars: should be equivalent to polars using `.is_null() | .is_nan()`, since distinguishes between the two.
* pandas: should be equivalent to `.isna()`, which flags both kinds of missingness.
* `sub_zero`
Currently, it is just using the formatter machinery. As I understand, substitutions should always go after formatters. (e.g. you should be able to `.sub_zero()` right away in a chain, and expect later `fmt_*()` calls to not override that.
Note these important pieces:
* Introduced new class `FormatterSkipElement`, which when returned from a format call, indicates that no change should be made.
* Rich, in his …
> feat: basic sub_missing and sub_zero

- great_tables/_utils_nanoplots.py
In a previous PR, a call to `_generate_nanoplot()` was simplified to use `**` to pass through args: 
https://github.com/posit-dev/great-tables/blob/cd618a4111b0f5206e412b522e2c50c06b2c9e8d/great_tables/_formats.py#L3832
However, the argument names in three cases don't match. These are:
- `line_type` != `data_line_type`
- `show_ref_line` != `show_reference_line`
- `show_ref_area` != `show_reference_area`
The solution here is to expand the shorter arg names to their longer counterparts. This doesn't break the GT API since the longer names are what the user has access to within `nanoplot_options()`.
With this change, examples in https://posit-dev.github.io/great-tables/blog/introduction-0.4.0/ should no longer be broken.
> Fix error from incorrectly passing nanoplot options to args in `_generate_nanoplot()` 

- docs/blog/design-philosophy/index.qmd
This updates the Design post to include links to the GH repo.
> Add links to GT repo throughout post

- great_tables/_export.py
- pyproject.toml
Existing README screenshot:
Shows support for Python 3.7, 3.8, and 3.9. The GitHub Actions test matrix shows `python-version: ["3.9", "3.10", "3.11", "3.12"]`.
This PR updates the supported Python version list to match what's tested.
- [n/a] I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
- [n/a] I have added **pytest** unit tests for any new functionality.
Fixes: https://github.com/posit-dev/great-tables/issues/220
> Update list of supported Python versions to match those tested

- .github/workflows/ci-tests.yaml
- great_tables/_data_color/base.py
- great_tables/_data_color/palettes.py
- pyproject.toml
- tests/data_color/__snapshots__/test_data_color.ambr
- tests/data_color/test_data_color_utils.py
This PR removes mizani as a dependency, so that we don't transitively depend on scipy and pandas. Note that our internal implementation does not depend on numpy, so that we can drop it as a dependency in a later PR.
This implementation is not as elegant as mizani's, or quite as optimized, but should do well for our purposes.
Our default implementation was about 50% slower than mizani in a simple test. But both are very fast for simple table displays (1.52 ms for 1,000 points for ours, 1ms for mizani.)
```python
from great_tables._data_color.palettes import GradientPalette, CoeffSequence
from mizani.palettes import gradient_n_pal
palette = GradientPalette(["red", "orange", "blue", "grey", "yellow", "red", "orange"])
palette2 = GradientPalette(["red", "orange", "blue", "grey", "yellow", …
```
> feat: remove mizani as dependency, re-implement logic internally

- great_tables/_formats.py
This PR removes some lingering uses of DataFrame methods outside of our DataFrame specific `_tbl_data.py` submodule. It also restricts the `columns=` argument of `.fmt_nanoplot()` to be a string for now, as this seemed to be the only supported path.
> fix: remove uses of DataFrame.apply and dtype methods

- great_tables/_helpers.py
I recommend utilizing the built-in `string` module to define the `letters` and `Letters` functions.
> Refactor `letters` and `Letters` functions in `_helpers`

- great_tables/_scss.py
- tests/test_scss.py
It appears we're having an issue with the [Table Theme Options -> Set options across table parts](https://posit-dev.github.io/great-tables/get-started/table-theme-options.html#set-options-across-table-parts) section. 
The problem seems to arise when color values are input using common names like `yellow` or `white`, causing the `font_color` not to transform them into the appropriate hexadecimal format.
To address this issue, I've implemented a conversion pattern similar to the one used in `font_color`, which should hopefully resolve the issue.
Additionally, I noticed quick returns in the first few lines of `font_color`. I'm uncertain whether these also need conversion. Could the team please review this aspect?
> Resolve issue with `table_font_color` not accepting named colors

- great_tables/_body.py
- great_tables/_boxhead.py
- great_tables/_databackend.py
- great_tables/_utils.py
Hello team, I've identified some potential improvements while reviewing the codebase.
> Various possible improvements

- great_tables/_utils_render_html.py
- tests/__snapshots__/test_export.ambr
- tests/__snapshots__/test_formats.ambr
- tests/__snapshots__/test_repr.ambr
- tests/__snapshots__/test_utils_render_html.ambr
- tests/data_color/__snapshots__/test_data_color.ambr
From a simple rendering of:
```python
GT(exibble, rowname_col="row", groupname_col="group").as_raw_html()
```
the following invalid HTML is generated for a group label row and the row below:
```html
<tbody class="gt_table_body">
<tr>
<tr class=gt_group_heading_row>  <th class="gt_group_heading" colspan="8">grp_a</th></tr>
<th class="gt_row gt_left gt_stub">row_1</th>
<td class="gt_row gt_right">0.1111</td>
<td class="gt_row gt_left">apricot</td>
<td class="gt_row gt_left">one</td>
<td class="gt_row gt_right">2015-01-15</td>
<td class="gt_row gt_right">13:35</td>
<td class="gt_row gt_right">2018-01-01 02:22</td>
<td class="gt_row gt_right">49.95</td>
</tr>
```
The first `<tr>` should instead be opening tag for the collection of `<th>` and `<td>` tags. …
> Ensure that group label rows have valid HTML

- great_tables/_spanners.py
- tests/test_spanners.py
Fix #313. 
```python
import polars.selectors as cs
exibble_pl = pl.from_pandas(exibble)
(
GT(exibble_pl)
.cols_hide(columns=cs.starts_with("date"))
)
```
> fix: Polars selectors error in `GT.cols_hide()`

- great_tables/_boxhead.py
- tests/test__boxhead.py
Fix #51. This PR focuses on adding tests for `cols_align`. 
During the process, I discovered that it should be feasible for `cols_align` to support `Polars` expressions. This enhancement is achieved by adding `sel_cols = resolve_cols_c(data=self, expr=columns)`.
> fix: add tests for `cols_align` and extend support for `Polars` expressions

- great_tables/_formats.py
- tests/__snapshots__/test_export.ambr
Fix #314.
At first, I attempted to address this issue by utilizing the check from `fmt_scientific` to verify `x`:
```python
if is_na(self._tbl_data, x):
return x
```
However, this caused a failure in `tests/test_export.py::test_html_string_generated`. Consequently, I opted to directly check whether `x` is `None` or not.
```python
exibble_pl = pl.from_pandas(exibble)
GT(exibble_pl).fmt_number(columns="num")
```
> fix: missing values in `fmt_number`

- great_tables/_utils_nanoplots.py
- tests/test__utils_nanoplots.py
Fix #279 . This PR aims to improve the display of integer or integerlike values in nanoplots. During the implementation, I came across two interesting findings in the code:
* Some locales may use the minus symbol `−` instead of `-`. Therefore, a conversion like `str(n).replace("−", "-")` might be necessary.
* The negative values appear to be handled appropriately with this approach.
```python
from great_tables import GT
random_numbers_df = pl.DataFrame(
{
"i": range(1, 5),
"lines": [
"20 23 6 7 37 23 21 4 7 16",
"2.3 6.8 9.2 2.42 3.5 12.1 5.3 3.6 7.2 3.74",
"-12 -5 6 3.7 0 8 -7.4",
"-12 0 15 7 8 10 1 24 17 13 6", # negative values should be ok
],
}
).with_columns(bars=pl.col("lines"))
(
GT(random_numbers_df, rowname_col="i")
.fmt_nanoplot(columns="lines") …
```
> fix: the display issue of integerlike values in nanoplots

- tests/test_spanners.py
Related to #35.
This PR aims to enhance test coverage for `cols_move`, `cols_move_to_start`, `cols_move_to_end`, and `cols_hide` functions in both `Pandas` and `Polars`. 
Meanwhile, given the substantial reliance on column selection within the `fmt_*` functions, should we conduct thorough tests for them using `Polars` selectors, or are we satisfied with the current state?
> Enhance test coverage for column selection

- great_tables/_styles.py
- tests/test_styles.py
It seems that the following code does not render as expected when `sides` is set to "all" for `style.borders`. The main reason might be the omission of other values while constructing a new `CellStyleBorders`.
```python
from great_tables import GT, md, html, style, loc
from great_tables.data import islands
islands_mini = (
pl.from_pandas(islands).sort("size", descending=True)
.head(10)
)
(
GT(islands_mini)
.tab_style(
style=style.borders(sides=["all"], style="solid", weight="4px", color="red"),
locations=loc.body(rows=[-1])
)
)
```
The table comparison before and after fixing can be found as below:
> fix: `CellStyleBorders` is not properly constructed when `sides` is set to "all"

- great_tables/_formats.py
- tests/test_formats.py
This PR fixes a bug, where fmt_image errored on missing values.
> Fix fmt_image erroring on missing values

- great_tables/_spanners.py
- great_tables/_utils_render_html.py
- tests/__snapshots__/test_utils_render_html.ambr
- tests/test_spanners.py
- tests/test_utils_render_html.py
Support more than 1 level of spanners:
```python
(
GT(exibble)
.tab_spanner("A", ["num", "char", "fctr"])
.tab_spanner("B", ["fctr"])
.tab_spanner("C", ["num", "char"])
.tab_spanner("D", ["fctr", "date", "time"])
.tab_spanner("E", spanners=["B", "C"])
)
```
NOTE:
- I made a design tweak with the underscore under upper level spanners
- Ref: #221
Fixes: https://github.com/posit-dev/great-tables/issues/273
Fixes: https://github.com/posit-dev/great-tables/issues/221
> Support N>1 spanners

- .github/scripts/save_browser_table.py
- .github/workflows/ci-tests.yaml
- Makefile
- great_tables/_export.py
- great_tables/_locale.py
- tests/test_export.py
- tests/test_formats.py
This PR refactors the `GT.save()` function to be a bit more robust, by...
* Screenshotting table element directly (prev screenshotted full window, then cropped using PIL)
* Dumping images into _browser-tests.html in our CI, and uploading as an artifact
* Supporting two debugging modes
- opening a debugging port (accessible via e.g. `chrome://inspect`)
- optionally dumping full browser screenshots with elements highlighted w/ borders (supports dumping at 3 stages: zoom, width_resize, final_resize). 
This PR supercedes (aka cribs) the best parts of...
* #276
* #300 
This PR should resolve...
* https://github.com/posit-dev/great-tables/issues/234
> fix: ensure export() always captures full table

- great_tables/_helpers.py
- tests/test__boxhead.py
- tests/test_helpers.py
- tests/test_locations.py
This PR tries to enhance our test coverage.
> Enhance the test coverage

- .github/workflows/ci-docs.yaml
This PR enables branches named `docs-preview-*` on our repo to deploy preview docs. This enables us to push specific PR branches from forks to our repo, to quickly preview.
> Ci docs preview

- docs/blog/polars-styling/index.qmd
- docs/blog/superbowl-squares/_code.py
- docs/get-started/basic-styling.qmd
- great_tables/_tbl_data.py
- tests/test_formats.py
- tests/test_tbl_data.py
Related to #340, [pola-rs/polars#16242](https://github.com/pola-rs/polars/issues/16242), [pola-rs/polars#16250](https://github.com/pola-rs/polars/issues/16250).
This PR provides a quick fix for the column selection logic in `Polars`. Further investigation may be needed from the team.
> fix: refactor column selection logic for `Polars`

- great_tables/_spanners.py
- tests/test_spanners.py
This PR aims to enhance the `cols_*()` functions by:
* Abstracting the validation of `sel_cols` into a separate function and adding related tests.
* Suggesting renaming `vars` to `col_vars` in the function. While `vars` might be acceptable in the function signature, it’s better to avoid using `vars` as a temporary variable name if possible.
* Updating the syntax for constructing the `DataFrame` in the `cols_*()` test functions.
> Enhance `cols_*()` functions

- docs/_quarto.yml
- docs/blog/index.qmd
This PR adds an RSS feed to the blog, following the instructions from [quarto](https://quarto.org/docs/websites/website-blog.html#rss-feed), and addresses the request in #115.
> docs: add RSS feed to blog

- great_tables/_spanners.py
- great_tables/_utils_render_html.py
- tests/test_spanners.py
Our project is progressing steadily, and it's been an enjoyable journey as one of the contributors. However, I've noticed that we might be overly reliant on the `list` type in the codebase. While `list` is excellent and suitable for prototyping, it can become problematic as the codebase grows. Therefore, I propose replacing `list` with `Generator` where possible.
I have chosen `seq_groups()` as a starting point since it is currently functioning as a kind of `Generator`. Currently, we request the input as a `list`, but I believe we can improve this by refactoring it to accept an `Iterable` as input. 
I hope this PR makes sense, and I welcome input from the team on this concept.
> Refactor `seq_groups()` to accept `Iterable`

- great_tables/_locations.py
- great_tables/_tbl_data.py
- tests/test_locations.py
- tests/test_tbl_data.py
This PR adds support for polars expressions to be used in column selection in addition to polars selectors. It requires polars v0.20.30, but falls back to the old behavior (or requiring a selector object) otherwise.
Note that this is the result of a chain of things:
* https://github.com/posit-dev/great-tables/pull/360
* https://github.com/pola-rs/polars/issues/16448
Which resulted in polars super quickly adding broader support for accepting Expressions and selectors that only result in column selection (and not e.g. transformation, or aliasing; PR https://github.com/pola-rs/polars/pull/16479).
I tried to give reasonably helpful error messages for people who are not on v0.20.3 that use Expr, but also suspect people will upgrade polaras patch versions fairly quickly.
```python
from …
```
> feat: support polars non-strict expand_selector

- great_tables/_data_color/palettes.py
- great_tables/_spanners.py
- great_tables/_utils.py
- great_tables/_utils_render_html.py
- tests/test_spanners.py
- tests/test_utils.py
This PR moves the `pairwise`, `seq_groups`, and `is_equal` functions to `_utils.py` since they are not specific to `_spanners.py`. Additionally, this PR updates `GradientPalette._create_coefficients` to leverage `pairwise`.
> Move `pairwise`, `seq_groups`, and `is_equal` functions to `_utils.py`

- docs/_quarto.yml
- docs/examples/index.qmd
- docs/get-started/basic-stub.qmd
- great_tables/_body.py
- great_tables/_gt_data.py
- great_tables/_modify_rows.py
- great_tables/_stub.py
- great_tables/_tbl_data.py
- great_tables/_utils_render_html.py
- great_tables/gt.py
- great_tables/utils_render_common.py
- tests/__snapshots__/test_modify_rows.ambr
- tests/test_gt.py
- tests/test_gt_data.py
- tests/test_modify_rows.py
- tests/test_tbl_data.py
- tests/test_utils_render_common.py
This WIP PR will enable options that currently must be set on construction of GT() to be set with methods.
The options are...
* rowname_col
* groupname_col
* auto_align
* id
* locale
The most challenging options are `rowname_col` and `groupname_col`, since setting these options means checking, and potentially undoing a number of things.
For example, a column that is being set to `rowname_col`, should:
* remove itself from any Spanner variable lists
* change its type in the Boxhead
* update the names in Stub.rows
Similarly, a new `groupname_col` will need to remove any styles that were set on it (when it was in the body).
This PR required a dive into components like Stub. While I was there, it seemed like a good idea to consolidate things into it, so that GT can't get into funky states, …
> Feat init methods

- great_tables/_data_color/base.py
- tests/data_color/__snapshots__/test_data_color.ambr
- tests/data_color/test_data_color.py
Related to #248.
This PR aims to support specifying a subset of rows in `GT.data_color()`. Based on the discussions, it appears that the most common use case involves excluding the last row, which is typically the total row. Consequently, rows that are not selected should not be included in the color "calculation." In this PR, I first select only the specified columns and rows, then "re-map" the "calculated color" back to the original table.
A simple example might illustrate the concept well:
```python
import polars.selectors as cs
from great_tables import GT
df = pl.DataFrame({"a": [1, 2, 3, 4, 5, 200], "b": [51, 52, 53, 54, 55, 200]})
GT(df).data_color(columns=cs.numeric(), rows=pl.col("a").lt(6), palette="PuBu")
```
```python
GT(df).data_color(columns=cs.numeric(), …
```
> Support specifying a subset of rows in `GT.data_color()`

- docs/_quarto.yml
- great_tables/_export.py
- great_tables/gt.py
- tests/test_export.py
This PR addresses #100 by adding a `GT.show()` method, which does the following:
* notebook-like environment: display table in cell output
* repl environment (e.g. ipython shell, python repl): open a browser with table
Fixes: #100
> Feat gt show

- docs/examples/index.qmd
- great_tables/_tbl_data.py
drive-by attempt at solving the issue I created. I'm sure there's a cleaner way to write this, but it unblocks me. feel free to push to this PR/request changes/close in favor of a better solution!
- Ref: #387
closes #387
> bug(polars): fix fmt_percent issue with polars-u64-idx

- docs/examples/index.qmd
- great_tables/_boxhead.py
- great_tables/_gt_data.py
- great_tables/_spanners.py
- tests/test_spanners.py
This PR allows for the use of units notation text in spanner labels (through `.tab_spanner()`). Here is an example of the intended usage:
```python
from great_tables import GT, md, system_fonts
from great_tables.data import reactions
import polars.selectors as ps
reactions_mini = (
pl.from_pandas(reactions)
.filter(pl.col("cmpd_type") == "mercaptan")
.select([
"cmpd_name",
"cmpd_formula",
ps.ends_with("k298")
])
.with_columns(
cmpd_formula=pl.concat_str(
"%" + pl.col("cmpd_formula") + "%"
)
)
)
(
GT(reactions_mini, rowname_col="cmpd_name")
.tab_header(title="Gas-phase reactions \
of selected mercaptan compounds")
.tab_spanner(
columns=ps.ends_with("k298"),
label = "Reaction Rate Constant (298 K),<br>{{cm^3 molecules^–1 s^–1}}"
)
.fmt_units(columns="cmpd_formula") …
```
> Feat: Allow spanners to use units notation in `.tab_spanner()`

- docs/examples/index.qmd
Made a change to the example tables in the docs. The latest version of Polars deprecates the **columns** argument in the pivot method, throwing an error in the docs. Changing the argument name to **on** should fix the error.
- Ref: #399
> Update polars examples for deprecated arg

- docs/_quarto.yml
- docs/get-started/index.qmd
I suggest mentioning that `Polars` DataFrame is supported in the `get-started` section. This should be an attractive point for users.
> docs: Mention support for `Polars` in the `get-started` section

- great_tables/_text.py
- great_tables/_utils_render_html.py
- great_tables/gt.py
- tests/__snapshots__/test_export.ambr
- tests/__snapshots__/test_formats.ambr
- tests/__snapshots__/test_repr.ambr
- tests/test_utils_render_html.py
This makes it so that `<thead>` doesn't just enclose the title/subtitle but rather both the header and column labels are included in a `<thead>` element. This is needed for overall compliance with HTML5 (this change eliminates the issue found through checking in https://validator.w3.org/) and though browsers can typically handle non-compliant HTML, Pandoc (thus GT tables rendered in Quarto) cannot.
Fixes: https://github.com/posit-dev/great-tables/issues/403
> fix!: ensure that `<thead>` element encloses both title/subtitle and column labels

- great_tables/_formats.py
- great_tables/_formats_vals.py
In several of the formatting methods, the common argument `force_sign=` erroneously mentions accounting notation. That feature does not yet exist in Great Tables so this text is removed here.
Fixes: https://github.com/posit-dev/great-tables/issues/241
> Remove mentions of `accounting` in `force_sign=` argument

- great_tables/_export.py
This PR is to address #424 
The challenge was that our resizing set the browser outer dimensions, but this does not account for space taken up by browser UI elements (which vary by browser). We had a "crud factor" set that basically accounted for this space by blissful accident.
`.save()` now explicitly tries to calculate the space between outer and inner browser dimensions, with a much smaller crud factor (to create some small padding around the table. This is important because table borders without crud factor might cause issues).
> fix: save with latest google chrome

- great_tables/_source_notes.py
- great_tables/_spanners.py
It seems we have two different signatures, `data: GTSelf` and `self: GTSelf`, to describe `GTSelf`. I propose we standardize the signature to `self: GTSelf`, as it is more commonly used in the repo.
> Standardize the `GTSelf` signature

- great_tables/_data_color/base.py
I propose changing the import statement in the `GT.data_color()` example to follow a more commonly used pattern.
> docs: update import statement in the `GT.data_color()` example

- great_tables/_spanners.py
In https://github.com/posit-dev/great-tables/issues/348 we wanted to ensure that the signature of `tab_spanner()` has been updated with types that indicate `md()` and `html()` could be used in the `label=` argument. This was done in a previous PR.
A second requirement was update the logic to use `isinstance()` checks rather than `hasattr()`. That change was made in this PR.
Fixes: https://github.com/posit-dev/great-tables/issues/348
> fix: use `isinstance()` instead of `hasattr()`

- great_tables/_spanners.py
This is a simple documentation improvement for the `tab_spanner()` method. The `cols_label()` allows for the use of units notation syntax and has documentation to explain that. This was missing for `tab_spanner()` though it has equivalent functionality. This PR explains that units notation can be used in `tab_spanner()`
Fixes: https://github.com/posit-dev/great-tables/issues/395
> docs: indicate that `tab_spanner()` allows for use of units notation in its `label=` arg

- great_tables/_gt_data.py
- great_tables/_scss.py
- great_tables/_spanners.py
- great_tables/_tbl_data.py
- great_tables/_utils.py
- tests/test_utils.py
Hello team,
I would like to propose consolidating the ordered list-related code using a new function, `_create_ordered_list()`.
Our current logic works well, such as `list({k: True for k in x})` in the `_unique_set()` function. However, even after working on the project for a while, I find it confusing to understand why the `True` is needed. It makes me question whether we need this Boolean value for some if-else logic. Eventually, I realize it's just a placeholder—a nice trick but not very intuitive.
A few hours ago, I came across [a post from Michael Driscoll on LinkedIn](https://www.linkedin.com/posts/driscollis_python-activity-7222631803080097792-XFrm/) and found that `list(dict.fromkeys(x).keys())` is more readable and neat, with a functional programming style. What do you think …
> Consolidate ordered list code using new `_create_ordered_list()` function

- docs/blog/pycon-2024-great-tables-are-possible/index.qmd
- docs/blog/tables-for-scientific-publishing/index.qmd
This updates two blogposts focused on PyCon 2024 and SciPy 2024 events. Some dead/non-working links are updated here. Additional links to new resources (recorded videos) are provided here.
Fixes: https://github.com/posit-dev/great-tables/issues/180
> docs: provide updates to PyCon- and SciPy-related blog posts

- great_tables/_formats.py
This PR focuses on cleaning up the import statements in `_formats.py`:
* Moved `import re` and `from dataclasses import dataclass` to the top, as they were previously placed near the end of the file.
* Removed the redundant local import of `import re`, now handled at the top level.
* Eliminated the local import of `from pathlib import Path` within a function, as `Path` is already imported at the top level and is required for type hints in other functions.
> Refactor import statements in `_formats.py`

- docs/blog/superbowl-squares/_code.py
I've noticed the CI is failing due to the `superbowl` example. This PR updates the example to be compatible with the latest version of `Polars`.
> docs: update `superbowl` example to align with the new version of `Polars`

- great_tables/_export.py
This PR addresses #414 by producing a full html page when using `.show()` to open a browser window. Previously, we only produced the table fragment, which for some reason caused the browser (or server) to screw up the encoding.
(The full html includes `<meta charset="utf-8"/>` which makes the encoding explicit)
> fix: use full html page in show() for correct utf-8 display

- great_tables/_export.py
I was wondering if `_save_screenshot()` could be improved by directly utilizing [`WebElement.screenshot_as_png`](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webelement.WebElement.screenshot_as_png).
> Update `_save_screenshot()` to use `WebElement.screenshot_as_png`

- docs/blog/superbowl-squares/index.qmd
@machow , it seems that the [deprecation warning](https://github.com/posit-dev/great-tables/pull/460#issuecomment-2371277167) is coming from the first code block in the `index.qmd`.
> docs: fix deprecation warning in the `superbowl` example

- docs/_quarto.yml
- great_tables/_gt_data.py
- great_tables/_options.py
- great_tables/_utils_render_html.py
- great_tables/css/gt_styles_default.scss
- tests/__snapshots__/test_export.ambr
- tests/__snapshots__/test_options.ambr
- tests/__snapshots__/test_repr.ambr
- tests/__snapshots__/test_scss.ambr
- tests/test_options.py
This PR addresses https://github.com/posit-dev/great-tables/issues/435 by making row striping options functional in rendered tables. An example of using row striping involves three new options in `tab_options()`:
```python
(
GT(exibble[["num", "char", "row", "group"]], rowname_col="row", groupname_col="group")
.tab_options(
row_striping_include_table_body=True,
row_striping_include_stub=True,
row_striping_background_color="lightblue"
)
)
```
Alternatively, the `opt_row_striping()` method allows for a simplified shortcut for `row_striping_include_table_body=True` so the user doesn't have to look through `tab_options()` for this basic functionality:
```python
(
GT(exibble[["num", "char", "row", "group"]], …
```
> feat: implement row striping options

- great_tables/_options.py
- tests/__snapshots__/test_options.ambr
- tests/test_options.py
This PR makes the following two changes to `opt_stylize()`:
- add the `add_row_striping=` argument to `opt_stylize()`
- include the table outline in some `opt_stylize()` styles
Now that row striping is functional with https://github.com/posit-dev/great-tables/pull/461 we can revisit the missing row striping in the table themes available through `opt_stylize()`. In the gt package (R), `opt_stylize()` has the `add_row_striping` arg and that's added in this PR (with a default of `True`).
Here's what the row striping looks like w/o and w/ this PR using this code:
```python
from great_tables import GT, exibble, md
(
GT(
exibble[["num", "char", "currency", "row", "group"]],
rowname_col="row",
groupname_col="group",
)
.tab_header(
title=md("Data listing from **exibble**"),
subtitle=md("`exibble` …
```
> feat!: add missing styling (including row striping) in `opt_stylize()`

- docs/_quarto.yml
Currently the `google_font()` helper function is missing from the package API reference in the site. This PR simply adds it in so it's visible (in time for the next release, `v0.12.0`).
> Include `google_font()` helper fn in API reference

- great_tables/_helpers.py
- tests/test_helpers.py
I’d like to propose using `type(self).__name__` to represent the class name, rather than hardcoding the class name directly.
> Update `__repr__()` for `GoogleFont`, `UnitStr` and `UnitDefinitionList`

- great_tables/_formats.py
- tests/test_formats.py
This PR addresses a potential bug where the global `locale` setting is not respected in `GT.fmt_*()` functions that accept `locale` as a parameter.
Consider the following example:
```python
(
GT(exibble[["currency"]])
.with_locale("ja")
.fmt_currency("currency")
)
```
It appears that the global `locale="ja"` setting is applied, but the output doesn't reflect this, and here’s what I expected:
The issue seems to stem from most of the formatting functions not fetching the global `locale` correctly. The line `locale = x._locale._locale if locale is None else locale` in `_resolve_locale()` is crucial to resolving this.
Therefore, I propose applying `_resolve_locale()` at the start of these formatting functions that accept the `locale` parameter. …
> fix: resolve global `locale` not being respected in `GT.fmt_*()` functions

- great_tables/_options.py
- tests/test_options.py
This PR updates the documentation to mention that the `font` parameter of `opt_table_font()` now accepts a `GoogleFont` object. It also consolidates the internal code and introduces additional tests.
> Update docs and code to support `GoogleFont` in `opt_table_font()` and add tests

- .github/workflows/ci-docs.yaml
- docs/_quarto.yml
This PR removes the redundant method documentation on the GT class page.
> docs: do not document GT members inline on its reference page

- .github/workflows/ci-docs.yaml
> docs: fix in headers causing their css classes get printed out

- great_tables/_export.py
- tests/test_export.py
addresses #416 by allowing a webdriver instance to be passed to `save(web_driver=...)`. This also addresses #479 by coercing file=Path(...) to a string.
Note that:
* Because we do context handling when we create web drivers, I wrapped any passed web drivers in a no-op context handler.
* Some arguments (like debug_port) that require setting options do not apply when a webdriver instance is passed.
> feat: allow passing a webdriver instance to save

- docs/_quarto.yml
- docs/get-started/basic-styling.qmd
- docs/get-started/loc-selection.qmd
- docs/get-started/table-theme-options.qmd
- docs/get-started/targeted-styles.qmd
- great_tables/_locations.py
- great_tables/_utils_render_html.py
- tests/test_locations.py
This PR addresses #466 by ensuring that group and row selection work across three scenarios:
* position number
* name string
* expression
> Fix locations: row and group selection

- great_tables/data/__init__.py
I’d like to propose adding a preview section to allow users to quickly glance at the built-in datasets. I believe this would help users choose the appropriate dataset for exploring the table.
> docs: add a preview section for the built-in datasets

- pyproject.toml
Addresses #476  (e.g. in GT.fmt_integer reference page)
> docs: update quartodoc to v0.8.1

- docs/_quarto.yml
Related to #451. 
I suggest exposing `vals.fmt_image()` in the documentation.
> docs: update `_quarto.yml` to expose `vals.fmt_image()`

- great_tables/_tbl_data.py
Polars has a few different installations options including:
* pip install polars
* pip install polars-u64-idx
* pip install polars-lts-cpu
The last one was not covered by the existing version check. This PR changes the version check to use `polars.__version__` which should work for all installation types. 
- Ref: #
> fix: use polars.__version__ in version check

- .github/workflows/ci-tests.yaml
- pyproject.toml
This update the metadata regarding support for Python 3.13
I added a CI build (the tests were passing locally)
> ci: add build for testing Python 3.13

- .github/CONTRIBUTING.md
Fixing a typo in the contributing guideline.
> docs: Fix spelling in the contributing guide

- great_tables/_export.py
- great_tables/_utils_selenium.py
- tests/test__utils_selenium.py
Related PR: #496.
This PR introduces several improvements to enhance the usability of `GT.save()`:
* Propose exposing `**params` to allow advanced users to customize save parameters directly via [Pillow](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save).
* Streamline the `.png` extension check to a single line.
* Construct the URL directly, similar to `FmtImage._get_image_uri()`, without using `tempfile.TemporaryDirectory()`.
* Replace the final `time.sleep(0.05)` with `WebDriverWait(driver, 1).until()` (we may need to determine the optimal timeout for most use cases).
* Remove the `.png` saving branch that relied on `selenium`; all files are now saved using `Pillow`.
* Suggest modifying `GT.save()` to return itself, allowing users to save intermediate …
> Improve `GT.save()` usability

- great_tables/_utils_nanoplots.py
- tests/test__utils_nanoplots.py
Hello Team,  
While reviewing these two functions, I noticed that a `ValueError` exception is created but not raised.  
I suspect this might be a bug, but please feel free to correct me if this behavior is intentional.
> Fix missing exception raise in `_val_is_numeric()` and `_val_is_str()`

- docs/_quarto.yml
This addresses a pyOpenSci reviewer comment. In the API reference section of the docs site, there is a note about a requirement for a Pandas installation when using any of the datasets from the `datasets` module.
Fixes: https://github.com/posit-dev/great-tables/issues/529
> docs: add text about Pandas req for use of datasets

- CITATION.cff
- README.md
This addresses a pyOpenSci reviewer comment related to citation information. The recommendation was to include a CITATION file and link to it from the README.md file (or other docs). Here, we have added the CITATION.cff file at the top level. A *Citation* section has been added to README.md file along with the bibtex citation text.
Fixes: https://github.com/posit-dev/great-tables/issues/531
> docs: add CITATION.cff file, link to CITATION text in README

- README.md
This PR addresses two recommendations from the pyOpenSci review of Great Tables. The first involves adding conda installation information. This has been added to README.md
Fixes: https://github.com/posit-dev/great-tables/issues/528
The second recommendation involves adding clarity on where GT code should be run (i.e., mostly in a notebook environment or in a Quarto doc). The README.md has been changed to address this in two paragraphs.
Fixes: https://github.com/posit-dev/great-tables/issues/530
> docs: Add conda install instructions and clarity on where to use GT in README.md

- README.md
This PR addresses an issue brought up in the pyOpenSci review of Great Tables. The problem is that the CI build badge was seen to be in a broken state (stuck on `"No Status"`. This is because the URLs used for the badge were malformed, and the changes here will fix that upon merging.
Fixes: https://github.com/posit-dev/great-tables/issues/546
> docs: fix URLs used CI badge in README

- great_tables/_formats.py
- great_tables/_formats_vals.py
- tests/__snapshots__/test_formats.ambr
- tests/test_formats.py
This introduces the `accounting=` arg to `fmt_number()`, `fmt_percent()`, `fmt_integer()` and `fmt_currency()`, allowing for accounting notation (e.g., `"-343.27"` -> `"(343.27)"`. This new functionality also extends to the same formatters in the `vals` module.
Here is an example table demonstrating usage:
```python
from great_tables import GT
df = pl.DataFrame(
{"number": [-1.2, 23.6], "percent": [-0.0523, 0.363], "integer": [2323, -23213], "currency": [-24334.23, 7323.253]}
).with_columns(number_acc = pl.col("number"), percent_acc = pl.col("percent"), integer_acc = pl.col("integer"), currency_acc = pl.col("currency"))
(
GT(df)
.fmt_number(columns="number")
.fmt_percent(columns="percent")
.fmt_integer(columns="integer")
.fmt_currency(columns="currency") …
```
> Feat: accounting notation for `fmt_number()`, `fmt_percent()`, `fmt_integer()` and `fmt_currency()`

- tests/__snapshots__/test_formats.ambr
- tests/test_formats.py
PR https://github.com/posit-dev/great-tables/pull/513 was merged before a final, desired change to a test/snapshot was added. This PR makes that change, and modifies the input table such that negative numbers are consistently in first row of the table, and positive values are in the second row.
Fixes: https://github.com/posit-dev/great-tables/issues/554
> test: update accounting table example test and snapshot

- .coveragerc
- pyproject.toml
This addresses a pyOpenSci reviewer comment related to test coverage reporting. The recommendation was to exclude `if TYPE_CHECKING:` lines from coverage reporting since the condition is always False at runtime. This is done here globally through the addition of a `.coveragerc` file.
Fixes: https://github.com/posit-dev/great-tables/issues/547
> chore: exclude `if TYPE_CHECKING:` lines from coverage reporting

- great_tables/_formats.py
- great_tables/_utils.py
- tests/test_formats.py
- tests/test_utils.py
Related PRs: #444, #451.
Currently, `GT.fmt_image()` supports formatting images from URLs by combining the `columns` and `path` parameters, as shown below:  
```python
from great_tables import GT, vals, html
img_path = "https://raw.githubusercontent.com/posit-dev/great-tables/refs/heads/main/great_tables/data/metro_images/"
df = pl.DataFrame({"lines": ["tram_T6.svg", "tram_T7.svg", "tram_T8.svg"]})
GT(df).fmt_image("lines", path=img_path)
```  
<hr>
This PR proposes an enhancement to allow image formatting using only the `columns` parameter, enabling the following code to execute without errors:  
```python
df2 = df.with_columns(pl.lit(img_path).add(pl.col("lines")).alias("lines"))
```  
```python
GT(df2).fmt_image("lines")  # It produces the same table as the original …
```
> Enhance `GT.fmt_image()` to support http/https schema in the `columns` parameter

- docs/get-started/index.qmd
This adds a note about the requirement for Pandas in the Get Started guide.
> docs: add note about pandas req in Get Started

- docs/blog/introduction-0.15.0/index.qmd
This adds the blog post for the v0.15.0 release of the package.
> blog: add the v0.15.0 release post

- docs/blog/introduction-0.15.0/index.qmd
This PR fixes a few mistakes in the text of the `0.15.0` release post.
> Fix some simple mistakes in blog post for the `0.15.0` release

- README.md
This PR adds two badges to the README: the DOI badge (c/o Zenodo) and the pyOpenSci reviewed badge (mark of successful package review). These additions partially fulfill the tasks outlined in the *Author Wrap Up Tasks*, found here: https://github.com/pyOpenSci/software-submission/issues/202#issuecomment-2569550522.
> docs: add pyOpenSci and DOI badges to README.md

- great_tables/_formats.py
- great_tables/_gt_data.py
- tests/test__boxhead.py
- tests/test_formats.py
Fix: #571  
It seems the issue stems from the input being a type we didn’t anticipate. While more advanced types like `pl.Enum`, `pl.Categorical`, `pl.Array`, `pl.List` or `pl.Struct` could introduce additional complexity, this PR addresses the simpler part for now.  
Since `_str_detect()` is clearly an internal function, we could consider modifying it. However, if we switch to using `re.search()`, the following test cases will fail:  
```bash
- FAILED `tests/test_formats.py::test_fmt_nanoplot_polars_listcol` - assert [- snapshot] == [+ received]  
- FAILED `tests/test_utils_render_html.py::test_render_polars_list_col` - assert [- snapshot] == [+ received]  
```
If we opt not to modify `_str_detect()`, we need to handle `uint` as a numerical type, as implemented in this PR. …
> fix: support `pl.UInt` type in nanoplot

- great_tables/_locations.py
- tests/test_tab_create_modify.py
Related Issue: #389.
Hello team,  
This is a rough idea for supporting the passing of `Polars` expressions to the `mask=` argument of `LobBody`.
The procedures are outlined as follows:  
1. Exclude the `stub` and `group` columns if necessary.  
2. Use `df.select()` to process the `Polars` expression and obtain a boolean-like matrix.  
3. Use two for-loops to iterate through the cells and select the desired cells based on whether their values are `True`.  
This idea is preliminary but should provide a foundation for further discussions.  
```python
from great_tables import GT, loc, style
from great_tables.data import gtcars
from polars import selectors as cs
df_mini = pl.from_pandas(gtcars).head().pivot(on="year", index=["trim", "mfr"], values="hp")
( …
```
> Support `mask=` argument in `LocBody`

- great_tables/data/__init__.py
This updates the dtype of the `year` col in the `gtcars` (from `float64` to `int64`).
> fix: update dtype of `year` col in `gtcars` dataset

- docs/blog/locbody-mask/index.qmd
Hello team,
I'd like to propose a blog post to promote the new `mask=` parameter in `loc.body()`. Feedback is always welcome!
The post is relatively short, and perhaps the team could extract some content to incorporate into the release blog for `0.16.0`.
> blog: add blog post promoting the `mask=` parameter in `loc.body()`

- .github/CODEOWNERS
- .github/workflows/ci-tests.yaml
This PR moves our pypi-token into a github environment, so we can require review before a github release pushes to pypi.
> ci: use deploy-pypi environment

- docs/get-started/basic-styling.qmd
- docs/get-started/loc-selection.qmd
- great_tables/_locations.py
Hello team,
This PR updates the documentation related to the `mask=` parameter in `loc.body()`. 
Additionally, it addresses a bug where error messages were not being rendered correctly.
> docs: update the related docs about `mask=` parameter in `loc.body()`

- great_tables/_export.py
Related issues: #518, #596.  
The `base64` encoding does not seem to be a suitable choice for `GT.save()`, as it has caused multiple issues. Therefore, I suggest rolling back to the previous working approach.
> fix: resolve encoding issue in `GT.save()`

- great_tables/_helpers.py
- great_tables/_utils_nanoplots.py
- tests/test__utils_nanoplots.py
This addresses #592 , I simply implemented the issue's author's fix. I added a new test that asserts the example passes without error. I'm happy to make any additions/changes to meet your project requirements!
> fix: correctly pass non-ints to nanoplot options

- great_tables/_formats_vals.py
- great_tables/_modify_rows.py
- great_tables/_spanners.py
Hello team,  
This PR improves our documentation by adding missing examples, primarily for the `vals` module. The goal is to provide simple code snippets that users can easily copy and run.
> docs: add examples to the documentation

- great_tables/_text.py
- great_tables/_utils_render_html.py
- tests/__snapshots__/test_export.ambr
- tests/__snapshots__/test_repr.ambr
- tests/__snapshots__/test_utils_render_html.ambr
- tests/test_utils_render_html.py
Previously, if you had multiple GT HTML tables inside a single document, that had column names in common, you would have repeated HTML ID attributes. This PR makes these ID attributes unique by prepending the table ID, if it exists.
- Ref: #594
> fix!: ensure HTML ID attributes are unique

- .github/workflows/ci-docs.yaml
- docs/_quarto.yml
- great_tables/_spanners.py
- great_tables/_styles.py
The `style.css` class has been available for awhile but it wasn't present in the API reference docs. This PR adds a basic docstring for `style.css` and makes it available in the docs.
Fixes: https://github.com/posit-dev/great-tables/issues/433
> docs: add `style.css` entry to API reference docs

- docs/_quarto.yml
- great_tables/_gt_data.py
- great_tables/_spanners.py
- great_tables/gt.py
- tests/test_spanners.py
Hello team,  
This PR ports the [cols_unhide()](https://gt.rstudio.com/reference/cols_unhide.html) function from `{gt}` to Great Tables.  
With this addition, users now have full control over column visibility at any state.  
Note that `Boxhead.set_cols_hidden()` and `Boxhead.set_cols_unhidden()` now rely on `Boxhead._set_cols_info_type()`.  
I'm unsure if this is the best approach—suggestions and feedback are welcome.
> feat: add `cols_unhide()` method

- great_tables/_export.py
I was looking for the `inline_css` arg in the html writer at work today, and noticed it wasn't there. The pr below simply exposes it as an argument.
- [ x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
- [ x] I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
- [ x] I have added **pytest** unit tests for any new functionality.
> Add inline_css argument

- great_tables/_export.py
- pyproject.toml
Given that `css-inline` does not work with pyodide and is really only ever used in `as_raw_html()`, this PR makes this library and optional dependency. It's placed in the 'extra' optional install group (along with packages for other export functions like `save()`).
Fixes: https://github.com/posit-dev/great-tables/issues/567
> fix!: move `css-inline` pkg to extra group

- docs/get-started/basic-styling.qmd
A frequent point of confusion is styling tables in VS Code using Jupyter and not seeing styles being applied. While we fixed a few issues with the display of tables there, it seems impractical to try to fix them all. A better recommendation is to view the table in a browser through `.show("browser")` when using VS Code.
To get the word out about this, it was brought up that a good place to inform users about this is in the docs. In this PR, a callout note is placed near the beginning of the [Styling the Table Body](https://posit-dev.github.io/great-tables/get-started/basic-styling.html) article in the Get Started guide.
Fixes: https://github.com/posit-dev/great-tables/issues/142
> docs: add note about using `.show("browser")` when in VS Code

- great_tables/_gt_data.py
- tests/test_export.py
Fixes: #640 
This PR adds support for pickling `GT`. The `__getnewargs__` method is relatively new to me, but the implementation appears to be straightforward.
Edit: Based on the error message, it seems that providing only the `data=` parameter is sufficient, but I'm unsure if the other three parameters—`auto_align=`, `rowname_col=`, and `groupname_col=`—are also required.
> feat: Support pickling

- great_tables/_formats.py
This PR removes the  `sep_mark=` parameter from `fmt_scientific()`. Its use was never implemented (and won't be) so it makes sense to remove it now.
Fixes: https://github.com/posit-dev/great-tables/issues/637
> fix: remove unused `sep_mark=` parameter from `fmt_scientific()`

- docs/blog/introduction-0.3.0/index.qmd
- docs/examples/index.qmd
- great_tables/_render_checks.py
- great_tables/_spanners.py
Hello team,
I noticed a warning message appearing in the documentation and would like to propose suppressing it for a better reading experience. I also corrected the function name in the warning message from `col_widths()` to `cols_width()`.
> docs: suppress the warning message from `cols_width()` in the docs

- great_tables/_formats.py
This  PR fixes several inconsistencies in the docstrings of the `fmt_date()`, `fmt_time()`, and `fmt_datetime()` methods. We remove mentions of non-existent `info_*()` functions and add docstring content for several parameters that were undocumented.
Fixes: https://github.com/posit-dev/great-tables/issues/657
> docs: update docstrings for date/time formatters

- tests/test_dependencies.py
This PR adds a test of a vals function, that demonstrates it working on a Polars series, without having Pandas installed.
This is intended to provide a simple test of https://github.com/posit-dev/great-tables/issues/675, showing Pandas is not required to use vals. However, it's fairly simple, so more testing / looking around may be needed.
> tests: add no pandas dependency test of vals function

- docs/_quarto.yml
- great_tables/_boxhead.py
- great_tables/gt.py
- tests/__snapshots__/test_boxhead.ambr
- tests/test_boxhead.py
Adding the cols_label_rotate method, which allows for rotating the column headers 90 degrees.
```python
from great_tables import GT, style, loc, exibble
exibble_sm = exibble[["num", "fctr", "row", "group"]]
(
GT(exibble_sm, rowname_col="row", groupname_col="group")
.cols_label_rotate(columns=["num", "fctr"])
.tab_style(
style=style.text(weight="bold"),
locations=loc.column_labels(["fctr"])
)
.tab_style(
style=style.text(size="22px"),
locations=loc.body(columns=["fctr"], rows=[4, 5, 6, 7]),
)
)
```
Fixes: #620
> docs: add cols_label_rotate method

- great_tables/_export.py
This PR fixes inconsistencies in the documentation of the `as_raw_html()` method. The description part of the docstring now explains each of the boolean parameters in terms of the intended effect and potential use cases. And `all_important=` is now included in the Parameters sections.
Fixes: https://github.com/posit-dev/great-tables/issues/685
> docs: improve docstring for the `as_raw_html()` method

- docs/get-started/index.qmd
This PR addresses a point of confusion when using GT outside of a notebook environment (e.g., console use). Previously there was a comment in the code cell that pointed toward the `show()` method. To address this better, I think it's worthwhile having a short sentence (with interlink to docs) about `show()` just below the example in a more prominent callout.
Fixes: https://github.com/posit-dev/great-tables/issues/619
> docs: introduce use of `show()` method in a callout

- great_tables/_data_color/base.py
- great_tables/_locations.py
- tests/test_substitutions.py
Replaces `.columns` with `get_column_names` to return column names also for pyarrow (currently the column values are returned).
For pyarrow backed tbl_data, `data_color` the code would end up breaking a few lines down the line when performing the follow operation:
```py
column_vals = data_table[col][row_pos].to_list()
```
In fact, slicing with a list on a chunked array raises 
> *** TypeError: 'list' object cannot be interpreted as an integer
I wanted this PR to be atomic enough to solve _one_ issue. I can follow up on this other one
- Closes #667
> fix: Always access column names via `get_column_names` instead of `.columns`

- great_tables/_data_color/base.py
- great_tables/_data_color/palettes.py
- great_tables/_tbl_data.py
- great_tables/_utils_nanoplots.py
- pyproject.toml
- tests/test__utils_nanoplots.py
Hi maintainers, I'm seeing if numpy could be removed from the dependencies in order to make the library more agnostic. I know this was a a discussion some time back but wasn't prioritized.
Personally, I'd love to drop numpy from some production images at my work.
I don't believe this current pr has any issues, but it's tough to tell since you're obviously testing it with a full dependency graph available. For this reason I'm marking it as a draft until I'm more confident!
Would love feedback/criticism
> Remove numpy from dependencies

- docs/_quarto.yml
- docs/get-started/extensions.qmd
This adds a get-started subpage which is a guide page on extensions, with gt-extras as an reference point.
The goal is to help people make their own personal "gt-extras" packages.
> docs: Extending Great Tables

- great_tables/_data_color/base.py
- tests/data_color/test_data_color_utils.py
See related issue. This PR relies on the fact that background that are not fully opaque are always blended against a white background. I think the way tables set final cell and other background colors is consistent with this fact, but I am open to being corrected and looking for a workaround if that isn't the case.
The PR effectively replaces `_remove_alpha()` with `_alpha_composite_with_white()`.
- Ref: Closes #746
> Fix: `_ideal_fgnd_color()` takes alpha into account

- docs/_quarto.yml
This adds the 'Supported by Posit' badge in the header of the project website (https://posit-dev.github.io/supported-by-posit/).
> docs: Include Posit badge in header of project website
