posit-dev/great-tables

AUTHORS.rst, README.md, docs/articles/intro.qmd, pyproject.toml
From pairing -- I've added myself to authors wherever I could find that stuff! Feel free to change anything -- I wasn't sure what to put for the maintainers blurb, so added myself there, but I'm not strongly wed to my name being in any particular spot!
=> docs: add michael to authors

docs/_quarto.yml, docs/examples/index.qmd, great_tables/_gt_data.py, great_tables/_tbl_data.py
This PR adds an extremely rudimentary docs site. I realized there are a ton of examples throughout the R gt docs, and it was helpful to try recreating some!
I also added support for using a polars DataFrame when groupname_cols is passed!
=> Docs examples

tests/test_tab_create_modify.py
This PR adds a test to tab create modify that checks when we select multiple columns for styling
=> Test tab create modify

great_tables/gt.py, tests/__snapshots__/test_formats.ambr, tests/test_formats.py
This fixes an issue where formatting methods had no effect on the final rendering of a table.
=> Rendering fix

docs/_quarto.yml, great_tables/_options.py
This adds `tab_options()`, which allows for the setting of a wide range of table options.
=> Add the `tab_options()` method

docs/blog/introduction-0.3.0/index.qmd
This adds the blog post for the `v0.3.0` release of the package.
=> Add the `v0.3.0` release post

docs/get-started/nanoplots.qmd, great_tables/_formats.py
Since nanoplots is a very new feature (with less testing than the usual), we are placing a warning noting that this feature is currently experimental. This will be removed once adequate tests are in place.
=> Add warning callout for experimental status

docs/blog/introduction-0.4.0/index.qmd
This adds the blog post for the `v0.4.0` release of the package.
=> Add the v0.4.0 release post

.github/workflows/ci-tests.yaml, Makefile
Pairing w/ Rich, this PR pushes coverage to CodeCov.
=> ci: workflow pushes to CodeCov

README.md
This adds documentation site and codecov badges to the README.md file.
=> Add docs site and codecov badges

docs/examples/index.qmd
Very minor documentation change to improve readability. See details in the linked issue.
- Ref: #263
=> fix(docs): rename variables on example code for Oceania

docs/examples/index.qmd
This PR provides light improvements to two examples in the Examples section of the project website.
=> Improve two examples in Examples section

great_tables/_locale.py, great_tables/_scss.py
This PR fixes some small cases, where files were being opened outside of a context manager.
=> fix: close some opened files

great_tables/_formats.py, great_tables/_utils_nanoplots.py, tests/test__utils_nanoplots.py, tests/test_formats.py
=> fix: do not fail for lists of large integers

pyproject.toml
remove webcolors in `pyproject.toml
- Ref: #282
=> chore: remove webcolors

great_tables/_render.py, tests/__snapshots__/test_repr.ambr, tests/test_repr.py
> Thank you for contributing to **great_tables**... this is great! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
- Ref: extending functionality originally planned in https://github.com/posit-dev/great-tables/issues/228
=> Add render target for html pages

great_tables/_export.py
This PR addresses https://github.com/posit-dev/great-tables/issues/381, by...
* not raising at the end of every `.show()` call
* not logging http request info to stderr (which `http.server` handlers do by default)
=> fix: show no longer raises or prints to stderr

docs/blog/tables-for-scientific-publishing/index.qmd, docs/examples/index.qmd, great_tables/_boxhead.py, great_tables/_gt_data.py, great_tables/_spanners.py
@rich-iannone feel free to push commits
Note that this PR includes https://github.com/posit-dev/great-tables/pull/393, as it's needed for the examples
=> docs: blog post Tables for Scientific Publishing

docs/blog/design-philosophy/index.qmd
BEFORE change:
- The nanoplot in the second example included more columns than described in the source note (i.e. days 3 through 9 plus "norm_I" and "norm_u" columns, instead of just days 3 through 8). AFTER change:
- The nanoplot includes days 3 through 9 only (without "norm_I" and "norm_u")
- The source note on table footer is adjusted accordingly
Additional tiny typos:
- Remove unused "import great_tables"
- Remove superfluous "the" in text paragraph (line 142)
Thank you for contributing to **great_tables**... this is great! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
- Ref: #
=> Tiny typo fixes and improvement suggestion to code example in "Design Philosophy" doc

great_tables/_helpers.py, great_tables/_options.py, tests/test_helpers.py, tests/test_options.py
This PR aims to improve the test coverage for `test_options.py`. I hope it helps!
=> Improve test coverage for `test_options.py`

docs/blog/introduction-0.12.0/index.qmd
This adds the blog post for the `v0.12.0` release of the package.
=> blog: add the v0.12.0 release post 

great_tables/data/__init__.py
Related PR: #586.
This PR updates the preview of the `year` column in `gtcars` dataset.
=> docs: update the preview of `year` col in `gtcars` dataset

great_tables/_export.py, tests/test_export.py
Addresses #593, but only writing png suffix if there is no suffix on file.
=> fix: do not always save screenshot as png

docs/get-started/index.qmd
align getting started guide with readme
https://github.com/posit-dev/great-tables/issues/619
=> doc: align getting started guide with readme

docs/blog/introduction-0.18.0/index.qmd
This adds the blog post that introduces the `v0.18.0` release.
=> blog: add the `v0.18.0` intro post

great_tables/_boxhead.py, great_tables/_data_color/base.py, great_tables/_export.py, great_tables/_formats.py, great_tables/_gt_data.py, great_tables/_helpers.py, great_tables/_locations.py, great_tables/_options.py, great_tables/_render.py, great_tables/_scss.py, great_tables/_spanners.py, great_tables/_styles.py, great_tables/_tbl_data.py, great_tables/_text.py, great_tables/_utils.py, great_tables/_utils_nanoplots.py, great_tables/_utils_render_html.py, great_tables/_utils_render_latex.py, tests/test_utils.py
So I might (or might not) have entered a rabbit hole, while the initial scope was much smaller (as you might tell from the branch name).
Some of the changes should lead to performance improvements, other are best practices.
Majority of them were spotted via [perflint](https://github.com/tonybaloney/perflint) or [refurb](https://github.com/dosisod/refurb).
There is no logic change, locally all tests pass without changing any of them.
---
If this is something of interest, feel free to help with the PR name, otherwise feel free to close it or cherry pick some of these changes.
NA
=> perf: Multiple nitpicks, some best practices and performances
